networks:
  my-network:
    driver: bridge

services:
  db:
    image: postgres:16.1
    restart: always
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=databasepg
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
      - ./dumps:/dumps
    networks:
      - my-network  

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 33080:3308
    environment:
      - MYSQL_DATABASE=databasemysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/mysql:/var/lib/mysql:rw
    networks:
      - my-network

